"""add project sections

Revision ID: 4e447593cc0a
Revises: 
Create Date: 2026-08-02 20:57:42.247838

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '4e447593cc0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('overview', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('dataset', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('methodology', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('results', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('challenges', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'challenges')
    op.drop_column('projects', 'results')
    op.drop_column('projects', 'methodology')
    op.drop_column('projects', 'dataset')
    op.drop_column('projects', 'overview')
    # ### end Alembic commands ###
